### PR TITLE
Updating Kevin Fong to fix the picture

### PR DESCRIPTION
**Pull request by ujamshed**
Hopefully fixed the issue with the picture of Kevin not loading up.

### CODE REVIEW

**Review by kevafong — APPROVED** [review]

**Comment by janash** [comment]
It seems like you have a merge conflict and it is saying it must be resolved using the command line! You should follow the instructions git gives under "view command line instructions". Namely, you should do

```
git fetch origin
git checkout -b Kevin_Fong2 origin/Kevin_Fong2
git merge main
```

I think I said earlier you wouldn't usually want to merge it. In this case, you will have to. The merge command will merge the main branch into the branch `Kevin_Fong2`.  Then, use `git status` to see what the conflicts are.

You will want to do a `git add` for the files you would like to keep, then do `git commit` to do a merge commit. After you've resolved the conflicts and made a merge commit, you will be able to push to this branch and merge.

**Comment by janash** [comment]
Let me know if you want more help on resolving this!

**Comment by ujamshed** [comment]
> Let me know if you want more help on resolving this!

Hi Dr. Nash,

When trying to execute the second command it says "fatal: A branch named 'Kevin_Fong2' already exists." So I can't merge the main into the Kevin_Fong2 branch.

**Comment by janash** [comment]
Okay, that's actually fine! This set of commands tells you how to get the branch if you don't already have it. So instead do

git switch Kevin_Fong2
git merge main

Then do git status. You can try to figure it out from there. Let me know if you want me to fix the merge!

**Comment by ujamshed** [comment]
> Okay, that's actually fine! This set of commands tells you how to get the branch if you don't already have it. So instead do
> 
> git switch Kevin_Fong2
> git merge main
> 
> Then do git status. You can try to figure it out from there. Let me know if you want me to fix the merge!

So I have done that, and now my branch Kevin_Fong2 and my local branch (origin/main) is 4 commits ahead of main, and its telling me to git push to main to publish my local commits... but I remember you telling us that we shouldn't push to main and that its protected, so I am unsure of what to do next.

**Review by kevafong — APPROVED** [review]

**Review by kevafong — APPROVED** [review]

**Review by kevafong — APPROVED** [review]

**Comment by janash** [comment]
@ujamshed You should be on the branch `Kevin_Fong2` when you do the merge and mark the merge conflict as being complete. Meaning when you do `git branch`, it will show `Kevin_Fong2` being your active branch instead of main.
You won't be able to push to main, but you should be able to do a `git push origin Kevin_Fong2`. If you've resolved the merge conflict, you should have a merge commit at least to push and then you should be able to merge into main from the pull request.

**Comment by ujamshed** [comment]
> @ujamshed You should be on the branch `Kevin_Fong2` when you do the merge and mark the merge conflict as being complete. Meaning when you do `git branch`, it will show `Kevin_Fong2` being your active branch instead of main.
> You won't be able to push to main, but you should be able to do a `git push origin Kevin_Fong2`. If you've resolved the merge conflict, you should have a merge commit at least to push and then you should be able to merge into main from the pull request.

It worked! Thanks so much! I am a little confused about how the conflict happened but maybe we can go over it tomorrow?

**Comment by janash** [comment]
We can try! I'm not quite sure what happened to be honest. The conflicts here were with whole files being added or deleted, rather than just conflicts in text. That's why it had to be fixed locally on the command line rather than GitHub (I can tell you that much)

**Pull request merged**
